import type { Metadata } from "next";
import "./globals.css";
import { Urbanist } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "../../context/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import QueryProvider from "../../context/query-provider";

const urbanist = Urbanist({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "AI Resume Builder",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn("bg-background", urbanist.className)}>
				<QueryProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
						<Toaster />
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
